### ISSUE TITLE
Failure for _ users

### ISSUE THREAD

**Issue by pascalrobert** [Jeija/od2samba4#1]
FYI, convert_users will fail for certains users, because their gidNumber is set to -2, and no group have this id. This is the case for "_krb_krbtgt". It will return:

> [root@dc1 od2samba4]# ./convert_users.py
> Connecting to Open Directory server
> Connecting to Samba4 server
> Retrieved user list with 145 user entries from Open Directory
> Building gidNumber to primaryGroupToken Dictionary for Primary Group Membership
> Traceback (most recent call last):
>   File "./convert_users.py", line 127, in <module>
>     user["primaryGroupID"] = [str(gid2rid[user["gidNumber"][0]])]
> KeyError: '-2'

I fixed this issue by creating a new group with this id, and I was able to run convert_users.py.

**Comment by mkuron** [comment]
Our Mac OS X 10.6 OpenDirectory didn't contain any such user, but I have seen it in the local directory domain on newer OSes. What OS version is yours running on? In the local directory domain, group -2 is nobody, so it should probably be mapped to Domain Guests.

However, there is probably no point in migrating _krb_krbtgt to Active Directory as it is likely some internal user account for Kerberos. Therefore, please feel free to submit a pull request adding that user to the blacklist in https://github.com/Jeija/od2samba4/blob/master/convert_users.py#L76

**Comment by pascalrobert** [comment]
10.9.4

**Comment by mkuron** [comment]
If you're running something newer than 10.6.8, you'll also need to make some small changes to the password hash extraction code as the newer versions run Heimdal instead of MIT Kerberos.
Relevant places: https://github.com/Jeija/od2samba4/tree/master/in and https://github.com/Jeija/od2samba4/blob/master/sync/sync.sh#L29 (kdb5_util cannot be used as it is MIT-specific and the master key would be stored in a different location) and https://github.com/Jeija/od2samba4/blob/master/extract_hashes.py#L32 (will need to specify that you are importing from a Heimdal dump instead of an MIT dump). This should be pretty easy to do, again we welcome pull requests.

**Comment by mkuron** [comment]
Original issue fixed in #2. Please create new issues and pull requests if you find anything else not working with your 10.9 server.

**Comment by andipilz** [comment]
Just in case someone once again has the same Problem:
I "hard wired" for the users which in my case are all primary Group in Open Directory on GID=20 "staff" to the PrimaryGroupID of "513".
In convert_users.py this is line 129 being `user["primaryGroupID"] = [str(gid2rid[user["gidNumber"][0]])]` to read `user["primaryGroupID"] = ["513"]`for this purpose.

**Comment by jpiel** [comment]
> 10.9.4

Did you ever do a dump of the kerberos database on you 10.9 server ? I can't find a way to do it on a 10.8...
